name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Install dependencies
        run: sudo apt-get install -y musl-tools

      - name: Build with Cargo
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Create ZIP file
        run: zip -j lambda.zip target/x86_64-unknown-linux-musl/release/your_lambda_function

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Upload to S3
        run: aws s3 cp lambda.zip s3://${{ secrets.AWS_BUCKET }}/lambda/lambda.zip

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template.yml \
            --stack-name your-stack-name \
            --capabilities CAPABILITY_IAM
