AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RustLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: rusty-lambda
      Handler: bootstrap
      Role: PLACEHOLDER_ROLE_ARN
      Code:
        S3Bucket: PLACEHOLDER_S3_BUCKET
        S3Key: lambda/lambda.zip
      Runtime: provided.al2
      MemorySize: 128
      Timeout: 30
