name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Install dependencies
        run: sudo apt-get install -y musl-tools

      - name: Build with Cargo
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Rename and create ZIP file
        run: |
          mv target/x86_64-unknown-linux-musl/release/rusty-lambda bootstrap
          zip lambda.zip bootstrap

      - name: Verify ZIP file contents
        run: unzip -l lambda.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          TIMESTAMP=$(date +%s)
          aws s3 cp lambda.zip s3://${{ secrets.AWS_BUCKET }}/lambda/lambda-$TIMESTAMP.zip
          echo "::set-output name=s3_key::lambda/lambda-$TIMESTAMP.zip"

      - name: Replace placeholders in CloudFormation template
        run: |
          sed -i 's|PLACEHOLDER_ROLE_ARN|arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_LAMBDA_EXECUTION_ROLE }}|' cloudformation-template.yml
          sed -i 's|PLACEHOLDER_S3_BUCKET|${{ secrets.AWS_BUCKET }}|' cloudformation-template.yml
          sed -i 's|lambda/lambda.zip|lambda/lambda-$TIMESTAMP.zip|' cloudformation-template.yml

      - name: Verify the CloudFormation template
        run: cat cloudformation-template.yml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template.yml \
            --stack-name dan-stack \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
